Update NvJitLinker API
gmarkall/nvjitlink-archive pull request #1
Opened 2023-06-20 19:30 UTC by brandon-b-miller

This PR updates the NvJitLinker API. Currently it does not pass tests and is WIP.

2023-06-28 14:03 UTC, gmarkall requested changes
Many thanks for the work porting the patch over! This is looking mostly good.

With the suggestions on the diff applied, the Numba testsuite patched with

```diff
diff --git a/runtests.py b/runtests.py
index 43dc271d5..b3df7e8ac 100755
--- a/runtests.py
+++ b/runtests.py
@@ -2,6 +2,9 @@
 import runpy
 import os
 
+from nvjitlink.patch import patch_numba_linker
+patch_numba_linker()
+
 if bool(os.environ.get('NUMBA_USE_TYPEGUARD')):
     # The typeguard import hook must be installed prior to importing numba.
     # Therefore, this cannot be part of the numba package.
```

only has three fails:

```
======================================================================
FAIL: test_set_registers_38 (numba.cuda.tests.cudadrv.test_linker.TestLinker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudadrv/test_linker.py", line 287, in test_set_registers_38
    self.assertLessEqual(compiled.get_regs_per_thread(), 38)
AssertionError: 78 not less than or equal to 38

======================================================================
FAIL: test_set_registers_57 (numba.cuda.tests.cudadrv.test_linker.TestLinker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudadrv/test_linker.py", line 282, in test_set_registers_57
    self.assertLessEqual(compiled.get_regs_per_thread(), 57)
AssertionError: 78 not less than or equal to 57

======================================================================
FAIL: test_set_registers_eager (numba.cuda.tests.cudadrv.test_linker.TestLinker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudadrv/test_linker.py", line 292, in test_set_registers_eager
    self.assertLessEqual(compiled.get_regs_per_thread(), 38)
AssertionError: 78 not less than or equal to 38
```

I think the `max_registers` kwarg of `PatchedLinker` is not working for some reason.

2023-06-28 14:03 UTC, gmarkall commented on nvjitlink/patch.py
> +required_numba_ver = (0, 56)
We should depend on at least 0.57 as that's the current version and I think there's no benefit to supporting older versions:

```suggestion
required_numba_ver = (0, 57)
```

2023-06-28 14:03 UTC, gmarkall commented on nvjitlink/patch.py
> +from ptxcompiler.patch import get_logger, patch_needed
We don't want to depend on `ptxcompiler` at all, since that shouldn't be used with CUDA 12.

2023-06-28 14:03 UTC, gmarkall commented on nvjitlink/patch.py
> +            f"See {mvc_docs_url} for more details.")
Numba 0.58 will also not have built-in support for nvjitlink, so we should for now only have a minimum version constraint - we can add an upper bound once there's a version of Numba that doesn't need the patch:

```suggestion
```

2023-06-28 14:03 UTC, gmarkall commented on nvjitlink/patch.py
> +    logger.debug("Creating new PatchedLinker")
The logging was more crucial when the patch decided whether to patch Numba (as in ptxcompiler / cubinlinker). For nvjitlink, I think we concluded that it's best for the "user" of nvjitlink to choose whether to patch, as it's the only entity with enough information to determine whether using nvjitlink is the right choice. So I think we can just get rid of all the logging calls to avoid our ptxcompiler dependency without losing anything important.

```suggestion
```

2023-06-28 14:03 UTC, gmarkall commented on nvjitlink/patch.py
> +def patch_numba_linker_if_needed():
If we call this, it should always patch the linker:
```suggestion
def patch_numba_linker():
```

2023-06-28 14:03 UTC, gmarkall commented on nvjitlink/patch.py
> +        logger.debug("Not patching Numba to use NvJitLinker")
Always patching the linker:

```suggestion
    Linker.new = new_patched_linker
```

2023-06-28 14:03 UTC, gmarkall commented on nvjitlink/patch.py
> +            raise LinkerError("Don't know how to link archives")
IIUC nvjitlink does know how to link archives, so we should link them instead of raising an exception (I think you can use the `NvJitLinker.add_library()` function for this).

2023-06-28 14:03 UTC, gmarkall commented on nvjitlink/patch.py
> +            ptx_compile_opts.append(arg)
This seems not to be working (maybe the option is not quite right for the nvJitLink API) - see my summary on the review.

2023-06-28 15:57 UTC, gmarkall commented on nvjitlink/patch.py
> +            raise LinkerError("Don't know how to link archives")
Actually... don't address that in this PR, let's tackle it in a follow-up

2023-06-28 15:58 UTC, gmarkall commented on nvjitlink/patch.py
> +            ptx_compile_opts.append(arg)
Maybe this doesn't need to be addressed in this PR either.

2023-06-29 14:03 UTC, brandon-b-miller commented on nvjitlink/patch.py
> +            ptx_compile_opts.append(arg)
I think this problem puts the tests into a failing state, if we want to do this in a follow up, what of those tests?

2023-06-29 15:12 UTC, brandon-b-miller commented on nvjitlink/patch.py
> +            ptx_compile_opts.append(arg)
I managed to spot why this was going wrong, it was because for nvjitlink options are passed with a single hyphen. I also noticed that the init method of `PatchedLinker` was doings some things that seem applicable to `cubinlinker` but not `nvjitlink`. This should be fixed up in https://github.com/gmarkall/nvjitlink/pull/1/commits/97efb11a5643bb8d00a0b2448f8cbde042a7b43a.

2023-06-30 09:20 UTC, gmarkall approved these changes
With the updates I can now run the test suite and the only errors I get are related to not being able to link archives. I think these never showed up before because the linker ended up in an error state due to the bad options for register count, as you mentioned in another comment.

I think this is looking good, so is ready to merge!

2023-06-30 09:20 UTC, merged